step("help", "--help")
step("no arguments", lambda w: w.run())
step("unknown command", "frobnicate")
step("list-sources, empty", "list-sources")
for w in worlds.values(): seed_check(w)
step("add-source usage error", "add-source", "onlyone")
step("add-source (missing folder)", lambda w: w.run("add-source", w.src + "/nope", "/my-files/B"))
step("add-source second, non-ascii dest", lambda w: w.run("add-source", w.src, "/my-files/Café"))
step("list-sources", "list-sources")
step("remove-source usage", "remove-source")
step("remove-source 2", "remove-source", "2")
step("remove-source unknown id", "remove-source", "99")
step("remove-source not a number", "remove-source", "abc")
step("status", "status")
step("force-all (nothing)", "force-all")
step("force-all 1", "force-all", "1")
step("start", "start")
step("start 1", "start", "1")
step("stop", "stop")
step("install-units", "install-units")
step("install-units 15", "install-units", "15")
step("enable-timer", "enable-timer")
step("disable-timer", "disable-timer")
step("set-interval 45", "set-interval", "45")
step("set-interval bad", "set-interval", "x")
step("set-interval 0", "set-interval", "0")
import glob
for impl,w in worlds.items():
    for f in sorted(glob.glob(w.home+"/.config/systemd/user/**/*", recursive=True)):
        if os.path.isfile(f): print("   unit file", impl, os.path.relpath(f, w.home), open(f).read().replace("\n","|"))
